name: Build & Push

on:
  push:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      trigger_build: ${{ steps.trigger.outputs.specs }}
      containers: ${{ steps.filter_specs.outputs.changes }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Detect changes
      uses: dorny/paths-filter@v2
      id: trigger
      with:
        filters: |
          specs: 'specs/**'
    - name: Filter specs
      uses: dorny/paths-filter@v2
      id: filter_specs
      with:
        # TODO: find a way to wildcard that
        filters: |
          pywine: 'specs/pywine/**'
          wine: 'specs/wine/**'

  build_and_push:
    needs: changes
    if: needs.changes.outputs.trigger_build == 'true'
    strategy:
      matrix:
        container: ${{ fromJSON(needs.changes.outputs.containers) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          make ${{ matrix.container }}
      - name: Push
        run: |
          cd specs/${{ matrix.container }}
          make push
